version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - echo Installing dependencies...
            - npm ci
    pre_build:
        commands:
            - echo Running pre-build steps...
            - npm run lint || true
    build:
        commands:
            - echo Generating sitemap...
            - node scripts/generate-sitemap.js
            - echo Building site...
            - npm run build
    post_build:
        commands:
            - echo Optimizing assets...
            - echo Build completed on `date`

artifacts:
    files:
        - "**/*"
    base-directory: dist
    cache:
        paths:
            - "node_modules/**/*"
            - ".next/cache/**/*"
